version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: openpass
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openpass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build: ./server
    environment:
      DATABASE_URL: postgres://openpass:password@db:5432/openpass
      APP_URL: http://localhost:3000
      AUTH_URL: http://localhost:4000
    ports:
      - "4000:4000"
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data:
